More fremantle autobuild tests
git-svn-id: https://vcs.maemo.org/svn/osm2go/trunk@126 33a88ea1-378e-42d5-b688-df424f1c5956

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3802,8 +3802,9 @@ echo "$as_me: Configuring for Maemo $VERSION" >&6;}
 
 else
 
-    { echo "$as_me:$LINENO: WARNING: maemo-version not found" >&5
-echo "$as_me: WARNING: maemo-version not found" >&6;}
+    { { echo "$as_me:$LINENO: error: maemo-version not found" >&5
+echo "$as_me: error: maemo-version not found" >&2;}
+   { (exit 1); exit 1; }; }
 
 fi
 
