Use liblocation if available to access gps
git-svn-id: https://vcs.maemo.org/svn/osm2go/trunk@118 33a88ea1-378e-42d5-b688-df424f1c5956

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -644,6 +644,8 @@ osso_CFLAGS
 osso_LIBS
 hildon_fm_2_CFLAGS
 hildon_fm_2_LIBS
+liblocation_CFLAGS
+liblocation_LIBS
 gpsbt_CFLAGS
 gpsbt_LIBS
 EXTRA_OBJS
@@ -678,6 +680,8 @@ osso_CFLAGS
 osso_LIBS
 hildon_fm_2_CFLAGS
 hildon_fm_2_LIBS
+liblocation_CFLAGS
+liblocation_LIBS
 gpsbt_CFLAGS
 gpsbt_LIBS
 gtk_CFLAGS
@@ -1285,6 +1289,10 @@ Some influential environment variables:
               C compiler flags for hildon_fm_2, overriding pkg-config
   hildon_fm_2_LIBS
               linker flags for hildon_fm_2, overriding pkg-config
+  liblocation_CFLAGS
+              C compiler flags for liblocation, overriding pkg-config
+  liblocation_LIBS
+              linker flags for liblocation, overriding pkg-config
   gpsbt_CFLAGS
               C compiler flags for gpsbt, overriding pkg-config
   gpsbt_LIBS  linker flags for gpsbt, overriding pkg-config
@@ -3509,9 +3517,136 @@ fi
   CFLAGS="$CFLAGS $hildon_fm_2_CFLAGS"
   LIBS="$LIBS $hildon_fm_2_LIBS"
 
+  # prefer liblocation over gpsbt to control gps
   if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gps-bt\"") >&5
-  ($PKG_CONFIG --exists --print-errors "gps-bt") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liblocation\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liblocation") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for liblocation" >&5
+echo $ECHO_N "checking for liblocation... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$liblocation_CFLAGS"; then
+        pkg_cv_liblocation_CFLAGS="$liblocation_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liblocation\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liblocation") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_liblocation_CFLAGS=`$PKG_CONFIG --cflags "liblocation" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$liblocation_LIBS"; then
+        pkg_cv_liblocation_LIBS="$liblocation_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liblocation\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liblocation") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_liblocation_LIBS=`$PKG_CONFIG --libs "liblocation" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        liblocation_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "liblocation"`
+        else
+	        liblocation_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "liblocation"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$liblocation_PKG_ERRORS" >&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (liblocation) were not met:
+
+$liblocation_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables liblocation_CFLAGS
+and liblocation_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (liblocation) were not met:
+
+$liblocation_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables liblocation_CFLAGS
+and liblocation_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables liblocation_CFLAGS
+and liblocation_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables liblocation_CFLAGS
+and liblocation_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	liblocation_CFLAGS=$pkg_cv_liblocation_CFLAGS
+	liblocation_LIBS=$pkg_cv_liblocation_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	:
+fi
+    CFLAGS="$CFLAGS -DENABLE_LIBLOCATION $liblocation_CFLAGS"
+    LIBS="$LIBS $liblocation_LIBS"
+
+else
+
+    { echo "$as_me:$LINENO: WARNING: liblocation not found, trying deprecated gpsbt" >&5
+echo "$as_me: WARNING: liblocation not found, trying deprecated gpsbt" >&6;}
+
+    if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gpsbt\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gpsbt") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
@@ -3627,17 +3762,19 @@ else
 echo "${ECHO_T}yes" >&6; }
 	:
 fi
-    CFLAGS="$CFLAGS -DENABLE_GPSBT $gpsbt_CFLAGS"
-    LIBS="$LIBS $gpsbt_LIBS"
+      CFLAGS="$CFLAGS -DENABLE_GPSBT $gpsbt_CFLAGS"
+      LIBS="$LIBS $gpsbt_LIBS"
 
 else
-  { echo "$as_me:$LINENO: WARNING: No gpsbt found, disabling gps auto start!" >&5
-echo "$as_me: WARNING: No gpsbt found, disabling gps auto start!" >&6;}
+  { echo "$as_me:$LINENO: WARNING: No liblocation nor gpsbt found, disabling gps auto start!" >&5
+echo "$as_me: WARNING: No liblocation nor gpsbt found, disabling gps auto start!" >&6;}
+fi
+
 fi
 
   if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"tablet_browser_interface\"") >&5
-  ($PKG_CONFIG --exists --print-errors "tablet_browser_interface") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"tablet-browser-interface\"") >&5
+  ($PKG_CONFIG --exists --print-errors "tablet-browser-interface") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
@@ -3645,8 +3782,8 @@ fi
     CFLAGS="$CFLAGS -DENABLE_BROWSER_INTERFACE"
 
 else
-  { echo "$as_me:$LINENO: WARNING: No table-browser-interface found, disabling microb interface!" >&5
-echo "$as_me: WARNING: No table-browser-interface found, disabling microb interface!" >&6;}
+  { echo "$as_me:$LINENO: WARNING: No tablet-browser-interface found, disabling microb interface!" >&5
+echo "$as_me: WARNING: No tablet-browser-interface found, disabling microb interface!" >&6;}
 fi
 
   # maemo uses dbus for ipc with maemo mapper
@@ -4525,6 +4662,8 @@ osso_CFLAGS!$osso_CFLAGS$ac_delim
 osso_LIBS!$osso_LIBS$ac_delim
 hildon_fm_2_CFLAGS!$hildon_fm_2_CFLAGS$ac_delim
 hildon_fm_2_LIBS!$hildon_fm_2_LIBS$ac_delim
+liblocation_CFLAGS!$liblocation_CFLAGS$ac_delim
+liblocation_LIBS!$liblocation_LIBS$ac_delim
 gpsbt_CFLAGS!$gpsbt_CFLAGS$ac_delim
 gpsbt_LIBS!$gpsbt_LIBS$ac_delim
 EXTRA_OBJS!$EXTRA_OBJS$ac_delim
@@ -4537,7 +4676,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 75; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 77; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
